#!/bin/bash

echo ""
echo "Resumo - MySQL Server"

# Verificar a versão do MySQL
mysql_version=$(mysql --version)
echo "Versão: $mysql_version"

# Verificar o status do serviço MySQL
status=$(systemctl is-active mysql)

if [ "$status" == "active" ]; then
    echo "O servidor está ativo."
    mysql_server_url=$(ss -tulnp | grep mysql)
    echo "URL: $mysql_server_url"
elif [ "$status" == "inactive" ]; then
    echo "O servidor está inativo."
else
    echo "Erro ao verificar status do servidor."
fi
